### ISSUE TITLE
The 'Microsoft.ACE.OLEDB.12.0' provider is not registered on the local machine.

### ISSUE THREAD

**Issue by paolo-gold** [gldd-se/PostDredge-Public#39]
Using GLDD laptop.. MS Access 2016 is installed

**Comment by paolo-gold** [comment]
## List of OLE DB Providers

https://stackoverflow.com/a/48298700

```ps
PS C:\Users\JanGo> foreach ($provider in [System.Data.OleDb.OleDbEnumerator]::GetRootEnumerator())
>> {
>>     $v = New-Object PSObject
>>     for ($i = 0; $i -lt $provider.FieldCount; $i++)
>>     {
>>         Add-Member -in $v NoteProperty $provider.GetName($i) $provider.GetValue($i)
>>     }
>>     $v
>> }
```

SOURCES_NAME        : SQLOLEDB
SOURCES_PARSENAME   : {0C7FF16C-38E3-11d0-97AB-00C04FC2AD98}
SOURCES_DESCRIPTION : Microsoft OLE DB Provider for SQL Server
SOURCES_TYPE        : 1
SOURCES_ISPARENT    : False
SOURCES_CLSID       : {0C7FF16C-38E3-11d0-97AB-00C04FC2AD98}

SOURCES_NAME        : MSDataShape
SOURCES_PARSENAME   : {3449A1C8-C56C-11D0-AD72-00C04FC29863}
SOURCES_DESCRIPTION : MSDataShape
SOURCES_TYPE        : 1
SOURCES_ISPARENT    : False
SOURCES_CLSID       : {3449A1C8-C56C-11D0-AD72-00C04FC29863}

SOURCES_NAME        : SQLNCLI11
SOURCES_PARSENAME   : {397C2819-8272-4532-AD3A-FB5E43BEAA39}
SOURCES_DESCRIPTION : SQL Server Native Client 11.0
SOURCES_TYPE        : 1
SOURCES_ISPARENT    : False
SOURCES_CLSID       : {397C2819-8272-4532-AD3A-FB5E43BEAA39}

SOURCES_NAME        : ADsDSOObject
SOURCES_PARSENAME   : {549365d0-ec26-11cf-8310-00aa00b505db}
SOURCES_DESCRIPTION : OLE DB Provider for Microsoft Directory Services
SOURCES_TYPE        : 1
SOURCES_ISPARENT    : False
SOURCES_CLSID       : {549365d0-ec26-11cf-8310-00aa00b505db}

SOURCES_NAME        : SQLNCLI11 Enumerator
SOURCES_PARSENAME   : {8F612DD2-7E28-424f-A2FD-C2EECC314AA2}
SOURCES_DESCRIPTION : SQL Server Native Client 11.0 Enumerator
SOURCES_TYPE        : 2
SOURCES_ISPARENT    : False
SOURCES_CLSID       : {8F612DD2-7E28-424f-A2FD-C2EECC314AA2}

SOURCES_NAME        : Windows Search Data Source
SOURCES_PARSENAME   : {9E175B8B-F52A-11D8-B9A5-505054503030}
SOURCES_DESCRIPTION : Microsoft OLE DB Provider for Search
SOURCES_TYPE        : 1
SOURCES_ISPARENT    : False
SOURCES_CLSID       : {9E175B8B-F52A-11D8-B9A5-505054503030}

SOURCES_NAME        : MSDASQL
SOURCES_PARSENAME   : {c8b522cb-5cf3-11ce-ade5-00aa0044773d}
SOURCES_DESCRIPTION : Microsoft OLE DB Provider for ODBC Drivers
SOURCES_TYPE        : 1
SOURCES_ISPARENT    : False
SOURCES_CLSID       : {c8b522cb-5cf3-11ce-ade5-00aa0044773d}

SOURCES_NAME        : MSDASQL Enumerator
SOURCES_PARSENAME   : {c8b522cd-5cf3-11ce-ade5-00aa0044773d}
SOURCES_DESCRIPTION : Microsoft OLE DB Enumerator for ODBC Drivers
SOURCES_TYPE        : 2
SOURCES_ISPARENT    : False
SOURCES_CLSID       : {c8b522cd-5cf3-11ce-ade5-00aa0044773d}

SOURCES_NAME        : SQLOLEDB Enumerator
SOURCES_PARSENAME   : {DFA22B8E-E68D-11d0-97E4-00C04FC2AD98}
SOURCES_DESCRIPTION : Microsoft OLE DB Enumerator for SQL Server
SOURCES_TYPE        : 2
SOURCES_ISPARENT    : False
SOURCES_CLSID       : {DFA22B8E-E68D-11d0-97E4-00C04FC2AD98}

SOURCES_NAME        : MSDAOSP
SOURCES_PARSENAME   : {dfc8bdc0-e378-11d0-9b30-0080c7e9fe95}
SOURCES_DESCRIPTION : Microsoft OLE DB Simple Provider
SOURCES_TYPE        : 1
SOURCES_ISPARENT    : False
SOURCES_CLSID       : {dfc8bdc0-e378-11d0-9b30-0080c7e9fe95}

**Comment by paolo-gold** [comment]
## Minimal Reproducible Example

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Data.OleDb" Version="4.7.0" />
  </ItemGroup>
</Project>
```

```c#
class Program
{
    static void Main()
    {
        var filePath = ...
        using var connection = new System.Data.OleDb.OleDbConnection($@"Provider=Microsoft.ACE.OLEDB.12.0;Data Source={filePath}");
        connection.Open();
    }
}
```

```
System.InvalidOperationException: The 'Microsoft.ACE.OLEDB.12.0' provider is not registered on the local machine.
   at System.Data.OleDb.OleDbServicesWrapper.GetDataSource(OleDbConnectionString constr, DataSourceWrapper& datasrcWrapper)
   at System.Data.OleDb.OleDbConnectionInternal..ctor(OleDbConnectionString constr, OleDbConnection connection)
   at System.Data.OleDb.OleDbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningObject)
   at System.Data.ProviderBase.DbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
   at System.Data.OleDb.OleDbConnection.Open()
   at Program.Main() in C:\Users\JanGo\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 7
```

**Comment by paolo-gold** [comment]
## Error when trying to install [AccessDatabaseEngine_X64.exe](https://www.microsoft.com/en-us/download/details.aspx?id=13255)

![image](https://user-images.githubusercontent.com/59780670/72690021-8c0bfa00-3add-11ea-8c2e-acc0d0bb56f1.png)

**Comment by paolo-gold** [comment]
Better powershell script: https://sethjackson.github.io/2018/04/17/checking-registered-ole-db-providers-in-powershell/

**Comment by gojanpaolo** [comment]
Install both 32-bit and 64-bit Microsoft ACE OLEDB Provider
https://stackoverflow.com/questions/37710776/how-to-install-microsoft-ace-oledb-32-bit-with-office-64-bit

**Comment by gojanpaolo** [comment]
We'll release 32-bit and 64-bit PostDredge for now and provide documentation: https://gldd-se.github.io/PostDredge/install.html

**Comment by gojanpaolo** [comment]
Maybe we can use chocolatey to install 64-bit ACE always?
https://medium.com/@daniel.sagita/using-microsoft-access-in-net-core-b419dbeceab1

**Comment by rcriii42** [comment]
Ooooh, shiny! I like it!

**Comment by gojanpaolo** [comment]
https://www.google.com/amp/s/datasavvy.me/2017/07/20/installing-the-microsoft-ace-oledb-12-0-provider-for-both-64-bit-and-32-bit-processing/amp/


> 
Delete or rename the mso.dll registry value in the following registry key: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\14.0\Common\FilesPaths

Is this really needed?
I don't remember doing this on the gldd laptop.

**Comment by gojanpaolo** [comment]
See also: https://social.msdn.microsoft.com/Forums/en-US/abf34eea-1029-429a-b88e-4671bffcee76/why-cant-32-and-64-bit-access-database-engine-aceoledb-dataproviders-coexist

> The /passive trick won't work well: if office 2010 32 bit is installed and if 64-bit ace is installed with /passive, then **every** time you run Access 2010, you get an automatic installation routine that resets to the 32-bit drivers for office.

**Comment by gojanpaolo** [comment]
I still think that using the `/passive` workaround to install both 32 and 64 bit ACE OLEBD might bring up more issues.

The safest solution is to just publish 32 and 64 bit variants of PostDredge.

Hopefully we could stop using MDB files in the near future...

**Comment by gojanpaolo** [comment]
Another possible workaround:

1. Develop an 32-bit standalone application (e.g. console app)
2. PostDredge calls the 32-bit app to parse mdb files

issues:
- concurrent db access
  - can sqlite support this?
    - if not, PostDredge can wait for the console app to finish
- additional overhead to start and close another process (hopefully negligible)
- what if user has 64 bit ACE OLEDB?
